name: Sync Main to Dev

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed for pushing commits

jobs:
  sync-main-to-dev:
    uses: lferrarotti74/github-workflows-templates/.github/workflows/sync-main-to-dev.yml@6f0bc13b750f07060550740d41d6a3d95d5b1915
    with:
      source_branch: main
      target_branch: dev
