name: Sync Main to Dev

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed for pushing commits

jobs:
  sync-main-to-dev:
    uses: lferrarotti74/github-workflows-templates/.github/workflows/sync-main-to-dev.yml@93635d1857059b50c4910a0f57bd0b1a3aaf6eb8
    with:
      source_branch: main
      target_branch: dev
