name: Sync Main to Dev

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed for pushing commits

jobs:
  sync-main-to-dev:
    uses: lferrarotti74/github-workflows-templates/.github/workflows/sync-main-to-dev.yml@9947412795ffd259361db1e342572a980a6b8590
    with:
      source_branch: main
      target_branch: dev
