name: Sync Main to Dev

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed for pushing commits

jobs:
  sync-main-to-dev:
    uses: lferrarotti74/github-workflows-templates/.github/workflows/sync-main-to-dev.yml@472579106d3f35ae543624f91c5ff6ef08b8a758
    with:
      source_branch: main
      target_branch: dev
