name: Sync Main to Dev

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed for pushing commits

jobs:
  sync-main-to-dev:
    uses: lferrarotti74/github-workflows-templates/.github/workflows/sync-main-to-dev.yml@a429f52b9a7f75a13eb44935df3e6a4adc8e3431
    with:
      source_branch: main
      target_branch: dev
