name: Sync Main to Dev

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed for pushing commits

jobs:
  sync-main-to-dev:
    uses: lferrarotti74/github-workflows-templates/.github/workflows/sync-main-to-dev.yml@d41b01529c3bad32888a01d769b13cb6ba68d599
    with:
      source_branch: main
      target_branch: dev
