name: Sync Main to Dev

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed for pushing commits

jobs:
  sync-main-to-dev:
    uses: lferrarotti74/github-workflows-templates/.github/workflows/sync-main-to-dev.yml@c8b214f2bcfa77d6bc45e48abdbd2eeeba43e62c
    with:
      source_branch: main
      target_branch: dev
